name: music_player_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  path_provider: ^2.1.0
  cupertino_icons: ^1.0.8
  file_picker: ^12.1.2
  flutter_taglib: ^1.5.2   # <--- Nuevo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true