name: music_player_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  path_provider: ^2.1.0
  cupertino_icons: ^1.0.8
  file_picker: ^12.1.2
  flutter_taglib: ^1.5.2   # <--- Nuevo
  shared_preferences: ^2.2.2
  palette_generator: ^0.3.3+3
  audio_service: ^0.18.15
  taglib_ffi: ^0.1.0
  http: ^1.2.0
  archive: ^3.6.0
  path: ^1.9.0
  permission_handler: ^11.3.0
  flutter_inappwebview: ^6.1.5
  screenshot: ^3.0.0      # Para capturar el widget como imagen
  share_plus: ^13.3.0
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^8.0.0 # Para saber qué versión tiene el usuario instalada
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ojo.gif

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  # Opcional: Si quieres un color de fondo específico para el ícono adaptativo en Android
  # background_color: "#000000"